services:
  django:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             uvicorn alhadara.asgi:application --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks: ["shared"]

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
    command: --load-only en,ar --char-limit 5000 --req-limit 1000
    environment:
      - LT_CHAR_LIMIT=5000
      - LT_REQ_LIMIT=1000
    networks: ["shared"]


  rqworker:
    build: .
    command: python manage.py rqworker default
    volumes:
      - .:/app
    env_file:
      - .env
    networks: ["shared"]

  rqscheduler:
    build: .
    command: python manage.py rqscheduler
    volumes:
      - .:/app
    env_file:
      - .env
    networks: ["shared"]

  # Telegram Bot 1
  telegram_bot_1:
    build: .
    command: python manage.py run_bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped  # Auto-restart if crashes

  # Telegram Bot 2
  telegram_bot_2:
    build: .
    command: python manage.py run_file_bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped


networks:
  shared:
    external: true   # create once