# Generated by Django 5.1.7 on 2025-05-10 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Syrian number (09XXXXXXXX, +9639XXXXXXXX, or 009639XXXXXXXX)', regex='^(\\+?963|0{1,2}963)?9\\d{8}$')]),
        ),
    ]
