# Generated by Django 5.1.7 on 2025-05-10 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be: 09XXXXXXXX, +9639XXXXXXXX, or 009639XXXXXXXX', regex='^(09\\d{8}|\\+9639\\d{8}|00963\\d{8})$')]),
        ),
    ]
