# Generated by Django 5.1.7 on 2025-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_reset_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='screenshot_path',
            field=models.ImageField(upload_to='my_images/'),
        ),
    ]
