# Generated by Django 5.1.7 on 2025-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_depositrequest_screenshot_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='screenshot_path',
            field=models.ImageField(storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='deposit_screenshots/'),
        ),
    ]
