# Generated by Django 5.1.7 on 2025-05-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_depositrequest_screenshot_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='wallet',
        ),
    ]
