# Generated by Django 5.1.7 on 2025-05-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_depositrequest_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='screenshot_path',
            field=models.ImageField(upload_to='deposit_screenshots/'),
        ),
    ]
