# Generated by Django 5.1.7 on 2025-05-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.profile'),
        ),
    ]
