# Generated by Django 5.1.7 on 2025-05-31 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_profileimage_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studyfield',
            field=models.ForeignKey(blank=True, default='Null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.studyfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, default='Null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.university'),
        ),
    ]
