# Generated by Django 5.1.7 on 2025-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_request', 'Deposit Request'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('course_enrollment', 'Course Enrollment'), ('course_starting', 'Course Starting'), ('course_starting_soon', 'Course Starting Soon'), ('course_payment', 'Course Payment')], max_length=20),
        ),
    ]
