# Generated by Django 5.2.3 on 2025-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_request', 'Deposit Request'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('course_enrollment', 'Course Enrollment'), ('enrollment_canceled', 'Enrollment canceled'), ('enrollment_cancellation', 'Enrollment Cancelation'), ('course_payment', 'Course Payment'), ('course_starting', ' Course Starting')], max_length=100),
        ),
    ]
