# Generated by Django 5.2.3 on 2025-08-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_filestorage'),
        ('entranceexam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('text', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='english_level',
            field=models.ForeignKey(blank=True, help_text='English language level achieved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='english_profiles', to='entranceexam.languagelevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='french_level',
            field=models.ForeignKey(blank=True, help_text='French language level achieved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='french_profiles', to='entranceexam.languagelevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='german_level',
            field=models.ForeignKey(blank=True, help_text='German language level achieved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='german_profiles', to='entranceexam.languagelevel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spanish_level',
            field=models.ForeignKey(blank=True, help_text='Spanish language level achieved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spanish_profiles', to='entranceexam.languagelevel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_request', 'Deposit Request'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('course_enrollment', 'Course Enrollment'), ('enrollment_canceled', 'Enrollment canceled'), ('enrollment_cancellation', 'Enrollment Cancelation'), ('course_payment', 'Course Payment'), ('course_starting', ' Course Starting'), ('ewallet_withdrawal', 'eWallet Withdrawal'), ('ewallet_transfer_sent', 'eWallet Transfer Sent'), ('ewallet_transfer_received', 'eWallet Transfer Received'), ('password_changed', 'Password Changed')], max_length=100),
        ),
    ]
