# Generated by Django 5.2.3 on 2025-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_captcha_profile_english_level_profile_french_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('course_payment', 'Course Payment'), ('course_refund', 'Course Refund'), ('transfer', 'Transfer'), ('booking_payment', 'Booking Payment'), ('booking_refund', 'Booking Refund')], max_length=20),
        ),
    ]
