# Generated by Django 5.2.3 on 2025-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loyalty_points_awarded',
            field=models.BooleanField(default=False, help_text='True if points for this transaction have been awarded'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_request', 'Deposit Request'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('course_enrollment', 'Course Enrollment'), ('enrollment_canceled', 'Enrollment canceled'), ('enrollment_cancellation', 'Enrollment Cancelation'), ('course_payment', 'Course Payment'), ('course_starting', ' Course Starting'), ('ewallet_withdrawal', 'eWallet Withdrawal'), ('ewallet_transfer_sent', 'eWallet Transfer Sent'), ('ewallet_transfer_received', 'eWallet Transfer Received'), ('password_changed', 'Password Changed'), ('points_earned', 'Loyalty Points Earned'), ('complaint_submitted', 'Complaint Submitted'), ('complaint_resolved', 'Complaint Resolved'), ('feedback_submitted', 'Feedback Submitted'), ('course_discount_alert', 'Course Discount Alert'), ('wishlist_slot_available', 'Wishlist Course Slot Available'), ('scheduleslot_news', 'New Schedule Slot News'), ('exam_attempt_submitted', 'Entrance Exam Submitted'), ('exam_graded', 'Entrance Exam Graded')], max_length=100),
        ),
    ]
