# Generated by Django 5.2.3 on 2025-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_scheduleslotnews_homeworkgrade'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='related_lessons',
            field=models.ManyToManyField(blank=True, help_text='Lessons related to this question for revision feedback.', related_name='related_questions', to='lessons.lesson'),
        ),
    ]
