# Generated by Django 5.2.3 on 2025-07-09 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_related_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points for this question (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
