# Generated by Django 5.2.3 on 2025-09-05 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('financial_summary_period', 'Financial Summary (Time Period)'), ('statistical_summary_period', 'Statistical Summary (Time Period)'), ('feedback_summary', 'Feedback Summary (Time Period)'), ('complaints_summary', 'Complaints Summary (Time Period)'), ('schedule_slot_performance', 'Schedule Slot Performance'), ('student_performance', 'Student Performance Summary')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_id', models.CharField(blank=True, help_text='RQ Job ID', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parameters used for the report, e.g., dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_storage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filestorage')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
