# Generated by Django 5.1.7 on 2025-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursetype_category_course_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from')), ('valid_until__isnull', True), _connector='OR'), name='valid_until_after_valid_from'),
        ),
    ]
