# Generated by Django 5.1.7 on 2025-05-18 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_scheduleslot_valid_until_after_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(help_text='Must be at least 1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Must be at least 0.01', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Must be at least 1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Must be at least 0.01', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
