# Generated by Django 5.1.7 on 2025-05-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_duration_alter_course_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='unique_hall_schedule_per_day_time',
        ),
    ]
