# Generated by Django 5.1.7 on 2025-05-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_studyfield_university_remove_profile_national_id_and_more'),
        ('courses', '0009_remove_course_teacher_scheduleslot_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='courses.coursetype')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interest')),
                ('study_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.studyfield')),
            ],
            options={
                'unique_together': {('course_type', 'interest', 'study_field')},
            },
        ),
    ]
