# Generated by Django 5.1.7 on 2025-06-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_enrollment_enrolled_by_enrollment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
