# Generated by Django 5.1.7 on 2025-06-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_homework_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='schedule_slot',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
