# Generated by Django 5.2.3 on 2025-08-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_homework_course_remove_homework_lesson_and_more'),
        ('entranceexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_language',
            field=models.ForeignKey(blank=True, help_text='Required language for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_courses', to='entranceexam.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_language_level',
            field=models.ForeignKey(blank=True, help_text='Minimum language level required for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_courses', to='entranceexam.languagelevel'),
        ),
    ]
