# Generated by Django 5.2.3 on 2025-08-31 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_required_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_start_before_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_organization',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tutor',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2100, 1, 1)),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='headcount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ewallet', 'eWallet'), ('cash', 'Cash')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='private_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='hall',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='halls', to='courses.hallservice'),
        ),
    ]
