# Generated by Django 5.2.3 on 2025-09-03 18:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_courseimage_coursetypeicon_departmenticon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='For percentage: 1-99, For fixed: amount in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'start_date', 'end_date'], name='courses_cou_status_d310e3_idx'), models.Index(fields=['course', 'status'], name='courses_cou_course__4b5807_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date'), models.CheckConstraint(condition=models.Q(('discounted_price__lt', models.F('original_price'))), name='discounted_price_less_than_original')],
            },
        ),
    ]
