# Generated by Django 5.2.3 on 2025-09-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_coursediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscount',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='coursediscount',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('course',), name='one_active_discount_per_course'),
        ),
    ]
