# Generated by Django 5.2.3 on 2025-07-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
    ]
