# Generated by Django 5.2.3 on 2025-09-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltypoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='loyaltypoints.loyaltypoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
