# Generated by Django 5.2.3 on 2025-06-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_homework_course_remove_homework_lesson_and_more'),
        ('lessons', '0002_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('schedule_slot', 'lesson_order')},
        ),
    ]
