# Generated by Django 5.2.3 on 2025-06-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
    ]
