# Generated by Django 5.2.3 on 2025-07-06 16:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_scheduleslotnews_homeworkgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslotnews',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='news/files/'),
        ),
        migrations.AlterField(
            model_name='scheduleslotnews',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news/images/'),
        ),
    ]
