# Generated by Django 5.2.3 on 2025-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_privatelessonrequest_privatelessonproposedoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslotnews',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='news/files/'),
        ),
        migrations.AlterField(
            model_name='scheduleslotnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/'),
        ),
    ]
