# Generated by Django 5.2.3 on 2025-07-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_filestorage'),
        ('lessons', '0008_alter_scheduleslotnews_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslotnews',
            name='file_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filestorage'),
        ),
    ]
