# Generated by Django 5.2.3 on 2025-07-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_filestorage'),
        ('lessons', '0009_scheduleslotnews_file_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.RemoveField(
            model_name='scheduleslotnews',
            name='file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_storage',
            field=models.ForeignKey(blank=True, help_text='Uploaded file via Telegram', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filestorage'),
        ),
    ]
